export const authConstants = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
};
export const userConstants = {
  GET_REALTIME_USERS: ' GET_REALTIME_USERS',
  GET_REALTIME_CHAT_MESSAGE: ' GET_REALTIME_CHAT_MESSAGE',
  GET_REALTIME_GROUP_MESSAGE: ' GET_REALTIME_GROUP_MESSAGE',
};
